// Enhanced Course Data Models for Video Content Management
// This extends the existing course model with video-centric features

export interface CourseVideo {
  id: string;
  courseId: string;
  title: string;
  description: string;
  videoUrl: string;
  thumbnailUrl: string;
  duration: number; // in seconds
  order: number;
  isPreview: boolean; // Free preview video
  isPublished: boolean;
  resources?: CourseResource[];
  quiz?: VideoQuiz;
  transcript?: string;
  captions?: VideoCaption[];
  createdAt: Date;
  updatedAt: Date;
  processingJobId?: string;
}

export interface CourseResource {
  id: string;
  title: string;
  type: 'pdf' | 'link' | 'document' | 'presentation' | 'code' | 'download';
  url: string;
  fileUrl?: string; // For downloadable files
  fileSize?: number; // in bytes
  order: number;
  isRequired: boolean;
  description?: string;
}

export interface VideoQuiz {
  id: string;
  questions: QuizQuestion[];
  passingScore: number;
  timeLimit?: number; // in minutes
  allowRetakes: boolean;
  maxAttempts?: number;
}

export interface QuizQuestion {
  id: string;
  type: 'multiple-choice' | 'true-false' | 'short-answer' | 'essay';
  question: string;
  options?: string[]; // For multiple choice
  correctAnswer: string | string[];
  explanation?: string;
  points: number;
  order: number;
}

export interface VideoCaption {
  id: string;
  language: string;
  url: string;
  format: 'vtt' | 'srt';
  isAutoGenerated: boolean;
}

export interface EnhancedCourse {
  // Base course fields (from existing Course interface)
  id: string;
  title: string;
  description: string;
  shortDescription: string;
  slug: string;
  instructorId: string;
  instructorName: string;
  instructorBio?: string;
  instructorAvatar?: string;
  category: string;
  subcategory?: string;
  tags: string[];
  level: 'beginner' | 'intermediate' | 'advanced';
  language: string;
  price: number;
  currency: string;
  isFree: boolean;
  thumbnailUrl?: string;
  previewVideoUrl?: string;
  status: 'draft' | 'pending' | 'approved' | 'published' | 'archived';
  objectives: string[];
  prerequisites: string[];
  targetAudience: string[];
  difficultyScore: number;
  timeCommitment: string;
  certificateAvailable: boolean;
  rating?: number;
  ratingCount?: number;
  enrollmentCount?: number;
  completionCount?: number;
  averageRating?: number;
  isLaunched?: boolean;
  featured?: boolean;
  trending?: boolean;
  bestseller?: boolean;
  pricingOptions?: {
    oneTime?: number;
    monthly?: number;
    yearly?: number;
    lifetime?: number;
    custom?: { duration: string; price: number }[];
  };
  availabilitySchedule?: {
    startDate: Date;
    endDate?: Date;
    enrollmentDeadline?: Date;
    maxEnrollments?: number;
    currentEnrollments?: number;
  };
  enrollmentType?: 'instant' | 'scheduled' | 'subscription' | 'manual';
  createdAt: Date;
  updatedAt: Date;

  // NEW: Video Content Management
  videos: CourseVideo[];
  totalDuration: number; // Total course duration in seconds
  totalVideos: number;
  publishedVideos: number;
  previewVideos: number;
  
  // Enhanced Progress Tracking
  learningObjectives: string[];
  learningPath: LearningPathItem[];
  certificateTemplate?: string;
  
  // Content Management
  contentStatus: 'setup' | 'content-ready' | 'review' | 'published';
  contentQualityScore?: number;
  lastContentReview?: Date;
  
  // Engagement Analytics
  averageCompletionTime?: number; // in days
  engagementScore?: number;
  dropoutRate?: number;
  
  // Migration tracking
  originalServiceId?: string;
  migratedAt?: Date;
  migrationStatus?: string;
}

export interface LearningPathItem {
  id: string;
  type: 'video' | 'quiz' | 'assignment' | 'resource';
  title: string;
  description: string;
  order: number;
  isRequired: boolean;
  estimatedTime: number; // in minutes
  dependencies?: string[]; // IDs of items that must be completed first
}

export interface EnhancedCourseEnrollment {
  // Base enrollment fields
  id: string;
  courseId: string;
  studentId: string;
  enrolledAt: Date;
  progress: number;
  completedAt?: Date;
  status: 'active' | 'completed' | 'cancelled' | 'suspended';
  lastAccessAt?: Date;
  timeSpent: number;
  refundRequested: boolean;
  refundProcessed: boolean;

  // Enhanced Progress Tracking
  completedVideos: string[]; // Video IDs
  currentVideo: string;
  watchTime: number;
  videoProgress: VideoProgress[]; // Progress per video
  quizAttempts: QuizAttempt[];
  assignmentSubmissions: AssignmentSubmission[];
  notesCount: number;
  bookmarksCount: number;
  discussionPostsCount: number;
  
  // Goal Integration
  personalGoals: LearningGoal[];
  goalProgress: GoalProgress[];
  
  // Learning Analytics
  learningPath: string[]; // Completed learning path items
  streakDays: number;
  totalSessions: number;
  averageSessionTime: number;
  lastSessionAt: Date;
  
  // Certificate Management
  certificateIssued: boolean;
  certificateId?: string;
  completionDate?: Date;
  certificateUrl?: string;
  
  // Migration tracking
  originalBookingId?: string;
  migratedAt?: Date;
  migrationStatus?: string;
}

export interface VideoProgress {
  videoId: string;
  watchedDuration: number; // seconds watched
  totalDuration: number; // total video duration in seconds
  lastPosition: number; // last position in seconds
  completed: boolean;
  completedAt?: Date;
  watchSessions: WatchSession[];
}

export interface WatchSession {
  id: string;
  startTime: Date;
  endTime?: Date;
  duration: number; // in seconds
  startPosition: number;
  endPosition: number;
  device?: string;
}

export interface LearningGoal {
  id: string;
  title: string;
  description: string;
  targetDate?: Date;
  isCompleted: boolean;
  milestones: Milestone[];
  category: 'career' | 'skill' | 'personal' | 'certification';
  priority: 'low' | 'medium' | 'high';
}

export interface Milestone {
  id: string;
  title: string;
  description: string;
  targetDate?: Date;
  isCompleted: boolean;
  completedAt?: Date;
  relatedCourseId?: string;
  relatedVideoId?: string;
}

export interface GoalProgress {
  goalId: string;
  progressPercentage: number;
  completedMilestones: string[];
  currentMilestone?: string;
  lastUpdated: Date;
}

export interface QuizAttempt {
  id: string;
  quizId: string;
  videoId?: string;
  score: number;
  maxScore: number;
  passed: boolean;
  answers: QuizAnswer[];
  timeSpent: number; // in minutes
  startedAt: Date;
  completedAt: Date;
  attemptNumber: number;
}

export interface QuizAnswer {
  questionId: string;
  answer: string | string[];
  isCorrect: boolean;
  points: number;
}

export interface AssignmentSubmission {
  id: string;
  assignmentId: string;
  videoId?: string;
  title: string;
  content: string;
  attachments?: string[]; // File URLs
  score?: number;
  feedback?: string;
  status: 'submitted' | 'reviewed' | 'graded' | 'resubmit-requested';
  submittedAt: Date;
  reviewedAt?: Date;
  reviewedBy?: string; // Instructor ID
}

// Data Migration Interfaces
export interface ServiceToCourseMigration {
  migrateService(service: Service): EnhancedCourse;
  migrateBookingToEnrollment(booking: Booking): EnhancedCourseEnrollment;
}

export interface Service {
  id: string;
  title: string;
  description: string;
  category: string;
  consultantId: string;
  price: number;
  thumbnailUrl?: string;
  status: string;
  createdAt: Date;
  // Add other service fields as needed
}

export interface Booking {
  id: string;
  serviceId: string;
  studentId: string;
  consultantId: string;
  createdAt: Date;
  status: string;
  // Add other booking fields as needed
}

// Backward-compatible aliases used by services during migration.
export type CourseVideoModel = CourseVideo;
export type VideoProgressModel = VideoProgress;
export type LearningGoalModel = LearningGoal & { updatedAt?: Date };
export type GoalProgressModel = GoalProgress;
export type EnhancedCourseEnrollmentModel = EnhancedCourseEnrollment;

// Video Upload and Processing Interfaces
export interface VideoUploadRequest {
  courseId: string;
  title: string;
  description: string;
  file: File | Buffer;
  thumbnail?: File | Buffer;
  isPreview: boolean;
  order: number;
  captions?: File[];
  resources?: ResourceUpload[];
}

export interface ResourceUpload {
  title: string;
  type: CourseResource['type'];
  file: File | Buffer;
  description?: string;
  isRequired: boolean;
}

export interface VideoProcessingJob {
  id: string;
  courseId: string;
  videoId: string;
  status: 'uploading' | 'processing' | 'transcoding' | 'thumbnail-generation' | 'completed' | 'failed';
  progress: number; // 0-100
  originalUrl: string;
  processedUrls?: {
    hls?: string;
    dash?: string;
    mp4?: string;
  };
  thumbnailUrl?: string;
  error?: string;
  createdAt: Date;
  completedAt?: Date;
}

// Certificate System Interfaces
export interface CourseCertificate {
  id: string;
  courseId: string;
  studentId: string;
  enrollmentId: string;
  certificateUrl: string;
  issuedAt: Date;
  verificationCode: string;
  templateId?: string;
  instructorSignature?: string;
  issuerName: string;
  issuerTitle: string;
  completionDate: Date;
  isRevoked: boolean;
  revokedAt?: Date;
  revokeReason?: string;
}

export interface CertificateTemplate {
  id: string;
  name: string;
  description: string;
  templateUrl: string;
  thumbnailUrl: string;
  fields: CertificateField[];
  isActive: boolean;
  createdBy: string;
  createdAt: Date;
}

export interface CertificateField {
  id: string;
  type: 'text' | 'image' | 'date' | 'signature';
  label: string;
  defaultValue?: string;
  position: { x: number; y: number };
  size: { width: number; height: number };
  styling: {
    fontSize?: number;
    fontFamily?: string;
    color?: string;
    fontWeight?: string;
    alignment?: 'left' | 'center' | 'right';
  };
  isRequired: boolean;
}
