import { StyleSheet } from 'react-native';
import { COLORS } from '../core/colors';

export const bookedConsultantsStyles = StyleSheet.create({
  emptyContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    paddingHorizontal: 40,
    paddingVertical: 60,
  },
  emptyTitle: {
    fontSize: 24,
    fontWeight: 'bold' as const,
    color: COLORS.black,
    marginBottom: 12,
    textAlign: 'center' as const,
  },
  emptySubtitle: {
    fontSize: 16,
    color: COLORS.gray,
    textAlign: 'center' as const,
    lineHeight: 24,
    marginBottom: 30,
  },
  browseButton: {
    backgroundColor: COLORS.green,
    paddingHorizontal: 30,
    paddingVertical: 12,
    borderRadius: 8,
  },
  browseButtonText: {
    color: COLORS.white,
    fontSize: 16,
    fontWeight: '600' as const,
  },
  consultantsList: {
    paddingHorizontal: 16,
    paddingBottom: 20,
  },
  consultantCard: {
    backgroundColor: COLORS.white,
    borderRadius: 12,
    padding: 16,
    marginBottom: 16,
    shadowColor: COLORS.black,
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.1,
    shadowRadius: 3.84,
    elevation: 5,
  },
  cardHeader: {
    flexDirection: 'row' as const,
    alignItems: 'flex-start' as const,
    marginBottom: 16,
  },
  avatar: {
    width: 60,
    height: 60,
    borderRadius: 30,
    marginRight: 12,
    backgroundColor: COLORS.lightGray,
    borderWidth: 2,
    borderColor: COLORS.green,
  },
  consultantInfo: {
    flex: 1,
  },
  consultantName: {
    fontSize: 18,
    fontWeight: 'bold' as const,
    color: COLORS.black,
    marginBottom: 4,
  },
  consultantTitle: {
    fontSize: 14,
    color: COLORS.gray,
    marginBottom: 8,
  },
  ratingContainer: {
    flexDirection: 'row' as const,
    alignItems: 'center' as const,
    gap: 4,
  },
  rating: {
    fontSize: 14,
    color: COLORS.yellow,
    fontWeight: '600' as const,
    marginLeft: 2,
  },
  reviewCount: {
    fontSize: 12,
    color: COLORS.gray,
    marginLeft: 4,
  },
  statusBadge: {
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 16,
  },
  statusText: {
    fontSize: 12,
    fontWeight: '600' as const,
  },
  sessionDetails: {
    marginBottom: 16,
  },
  detailRow: {
    flexDirection: 'row' as const,
    alignItems: 'center' as const,
    marginBottom: 8,
  },
  detailText: {
    fontSize: 14,
    color: COLORS.black,
    marginLeft: 8,
  },
  progressContainer: {
    marginBottom: 16,
  },
  progressText: {
    fontSize: 14,
    color: COLORS.black,
    marginBottom: 8,
    fontWeight: '500' as const,
  },
  progressBar: {
    height: 6,
    backgroundColor: COLORS.lightGray,
    borderRadius: 3,
    overflow: 'hidden' as const,
  },
  progressFill: {
    height: '100%' as any,
    backgroundColor: COLORS.green,
    borderRadius: 3,
  },
  actionButtons: {
    flexDirection: 'row' as const,
    gap: 6,
    flexWrap: 'wrap' as const,
  },
  messageButton: {
    flex: 1,
    minWidth: 80,
    backgroundColor: COLORS.green,
    flexDirection: 'row' as const,
    alignItems: 'center' as const,
    justifyContent: 'center' as const,
    paddingVertical: 10,
    paddingHorizontal: 8,
    borderRadius: 8,
    gap: 4,
  },
  messageButtonText: {
    color: COLORS.white,
    fontSize: 12,
    fontWeight: '600' as const,
  },
  callButton: {
    flex: 1,
    minWidth: 80,
    backgroundColor: COLORS.blue,
    flexDirection: 'row' as const,
    alignItems: 'center' as const,
    justifyContent: 'center' as const,
    paddingVertical: 10,
    paddingHorizontal: 8,
    borderRadius: 8,
    gap: 4,
  },
  callButtonText: {
    color: COLORS.white,
    fontSize: 12,
    fontWeight: '600' as const,
  },
  reviewButton: {
    flex: 1,
    minWidth: 80,
    backgroundColor: COLORS.yellow,
    flexDirection: 'row' as const,
    alignItems: 'center' as const,
    justifyContent: 'center' as const,
    paddingVertical: 10,
    paddingHorizontal: 8,
    borderRadius: 8,
    gap: 4,
  },
  reviewButtonText: {
    color: COLORS.white,
    fontSize: 12,
    fontWeight: '600' as const,
  },
  browseAllButton: {
    backgroundColor: COLORS.green,
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 6,
  },
  browseAllText: {
    color: COLORS.white,
    fontSize: 12,
    fontWeight: '600' as const,
  },
  viewBookingsButton: {
    flexDirection: 'row' as const,
    alignItems: 'center' as const,
    justifyContent: 'center' as const,
    backgroundColor: COLORS.green,
    borderWidth: 1,
    borderColor: COLORS.green,
    paddingVertical: 12,
    paddingHorizontal: 16,
    borderRadius: 8,
    marginTop: 12,
    gap: 8,
  },
  viewBookingsText: {
    color: COLORS.white,
    fontSize: 14,
    fontWeight: '600',
  },
  debugContainer: {
    marginTop: 20,
    padding: 10,
    backgroundColor: COLORS.lightGray,
    borderRadius: 8,
  },
});
