import { StyleSheet } from 'react-native';
import { COLORS } from '../core/colors';

export const callingStyles = StyleSheet.create({
  // Original calling screen styles
  container: {
    flex: 1,
    backgroundColor: COLORS.green,
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  topBar: {
    width: '90%',
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: 20,
  },
  timeText: {
    color: COLORS.white,
    fontSize: 16,
    fontWeight: '600',
  },
  statusIcons: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  signalIcon: {
    width: 20,
    height: 12,
    backgroundColor: COLORS.white,
    borderRadius: 2,
  },
  wifiIcon: {
    width: 16,
    height: 12,
    backgroundColor: COLORS.white,
    borderRadius: 2,
  },
  batteryIcon: {
    width: 24,
    height: 12,
    backgroundColor: COLORS.white,
    borderRadius: 2,
  },
  profileContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    paddingHorizontal: 20,
  },
  profileImage: {
    width: 120,
    height: 120,
    borderRadius: 60,
    borderColor: COLORS.white,
    borderWidth: 3,
  },
  name: {
    color: COLORS.white,
    fontSize: 28,
    fontWeight: 'bold',
    marginTop: 20,
    textAlign: 'center',
  },
  status: {
    color: COLORS.white,
    fontSize: 18,
    marginTop: 8,
    opacity: 0.8,
    textAlign: 'center',
  },
  buttonContainer: {
    flexDirection: 'row',
    justifyContent: 'space-around',
    width: '80%',
    paddingHorizontal: 20,
  },
  iconButton: {
    width: 60,
    height: 60,
    borderRadius: 30,
    backgroundColor: COLORS.white,
    justifyContent: 'center',
    alignItems: 'center',
    shadowColor: COLORS.black,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 3,
  },
  hangupButton: {
    backgroundColor: COLORS.red,
    transform: [{ rotate: '135deg' }],
  },

  // Video calling screen styles
  videoCallContainer: {
    flex: 1,
    backgroundColor: COLORS.black,
  },
  mainVideoFeed: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    width: '100%',
    height: '100%',
  },
  topStatusBar: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: 20,
    paddingVertical: 10,
    zIndex: 10,
  },
  statusTime: {
    color: COLORS.white,
    fontSize: 16,
    fontWeight: '600',
  },
  videoStatusIcons: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  videoWifiIcon: {
    width: 16,
    height: 12,
    backgroundColor: COLORS.white,
    borderRadius: 2,
  },
  videoBatteryIcon: {
    width: 24,
    height: 12,
    backgroundColor: COLORS.white,
    borderRadius: 2,
  },
  bottomControls: {
    position: 'absolute',
    left: 0,
    right: 0,
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    gap: 20,
    zIndex: 10,
  },
  controlButton: {
    width: 50,
    height: 50,
    borderRadius: 25,
    backgroundColor: COLORS.white,
    justifyContent: 'center',
    alignItems: 'center',
    shadowColor: COLORS.black,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.2,
    shadowRadius: 4,
    elevation: 5,
  },
  videoHangupButton: {
    backgroundColor: COLORS.red,
  },
  insetVideoContainer: {
    position: 'absolute',
    right: 20,
    width: 100,
    height: 150,
    borderRadius: 10,
    overflow: 'hidden',
    zIndex: 10,
    borderWidth: 2,
    borderColor: COLORS.white,
  },
  insetVideo: {
    width: '100%',
    height: '100%',
  },
});
