import { StyleSheet } from 'react-native';
import { COLORS } from '../core/colors';

export const recruiterApplicationReviewScreenStyles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: COLORS.lightBackground,
  },
  scrollView: {
    flex: 1,
  },
  scrollContent: {
    padding: 16,
    paddingBottom: 24,
  },
  emptyContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
  },
  emptyText: {
    fontSize: 16,
    color: COLORS.gray,
  },
  matchBanner: {
    padding: 20,
    borderRadius: 16,
    marginBottom: 20,
  },
  matchBannerTitle: {
    fontSize: 22,
    fontWeight: '700',
    color: COLORS.white,
    marginBottom: 8,
    letterSpacing: 0.5,
  },
  matchBannerSubtitle: {
    fontSize: 16,
    color: COLORS.white,
    fontWeight: '500',
  },
  infoCard: {
    backgroundColor: COLORS.white,
    borderRadius: 16,
    padding: 20,
    marginBottom: 20,
    shadowColor: COLORS.black,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.08,
    shadowRadius: 8,
    elevation: 3,
  },
  cardTitle: {
    fontSize: 16,
    fontWeight: '600',
    color: COLORS.gray,
    marginBottom: 12,
  },
  applicantName: {
    fontSize: 22,
    fontWeight: '700',
    color: COLORS.black,
    marginBottom: 6,
  },
  applicantEmail: {
    fontSize: 15,
    color: COLORS.gray,
    fontWeight: '500',
  },
  section: {
    marginBottom: 24,
  },
  sectionTitle: {
    fontSize: 18,
    fontWeight: '700',
    color: COLORS.black,
    marginBottom: 16,
  },
  skillsGroup: {
    marginBottom: 20,
  },
  skillsGroupTitle: {
    fontSize: 15,
    fontWeight: '600',
    color: COLORS.green,
    marginBottom: 12,
  },
  skillsGroupTitleMissing: {
    fontSize: 15,
    fontWeight: '600',
    color: COLORS.red,
    marginBottom: 12,
  },
  skillsContainer: {
    flexDirection: 'row',
    flexWrap: 'wrap',
  },
  skillTag: {
    backgroundColor: COLORS.lightBackground,
    paddingHorizontal: 14,
    paddingVertical: 8,
    borderRadius: 8,
    marginRight: 10,
    marginBottom: 10,
  },
  skillText: {
    fontSize: 14,
    color: COLORS.black,
    fontWeight: '500',
  },
  skillTagMatched: {
    backgroundColor: COLORS.green,
    paddingHorizontal: 14,
    paddingVertical: 8,
    borderRadius: 8,
    marginRight: 10,
    marginBottom: 10,
  },
  skillTextMatched: {
    fontSize: 14,
    color: COLORS.white,
    fontWeight: '600',
  },
  experienceCard: {
    backgroundColor: COLORS.white,
    borderRadius: 12,
    padding: 16,
    marginBottom: 12,
    borderWidth: 1,
    borderColor: COLORS.lightBackground,
  },
  experienceTitle: {
    fontSize: 17,
    fontWeight: '700',
    color: COLORS.black,
    marginBottom: 6,
  },
  experienceCompany: {
    fontSize: 15,
    color: COLORS.gray,
    marginBottom: 4,
    fontWeight: '500',
  },
  experienceDate: {
    fontSize: 13,
    color: COLORS.gray,
    marginBottom: 8,
  },
  experienceDescription: {
    fontSize: 14,
    color: COLORS.black,
    lineHeight: 20,
  },
  educationCard: {
    backgroundColor: COLORS.white,
    borderRadius: 12,
    padding: 16,
    marginBottom: 12,
    borderWidth: 1,
    borderColor: COLORS.lightBackground,
  },
  educationDegree: {
    fontSize: 17,
    fontWeight: '700',
    color: COLORS.black,
    marginBottom: 6,
  },
  educationInstitution: {
    fontSize: 15,
    color: COLORS.gray,
    marginBottom: 4,
    fontWeight: '500',
  },
  educationYear: {
    fontSize: 13,
    color: COLORS.gray,
  },
  backgroundText: {
    fontSize: 15,
    color: COLORS.black,
    lineHeight: 24,
    backgroundColor: COLORS.white,
    padding: 16,
    borderRadius: 12,
  },
  coverLetterText: {
    fontSize: 15,
    color: COLORS.black,
    lineHeight: 24,
    backgroundColor: COLORS.white,
    padding: 16,
    borderRadius: 12,
  },
  resumeButton: {
    backgroundColor: COLORS.green,
    padding: 16,
    borderRadius: 12,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 10,
  },
  resumeButtonText: {
    color: COLORS.white,
    fontSize: 16,
    fontWeight: '600',
  },
  statusButtonsContainer: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    marginBottom: 16,
    gap: 10,
  },
  statusButton: {
    backgroundColor: COLORS.lightBackground,
    paddingHorizontal: 18,
    paddingVertical: 12,
    borderRadius: 10,
    marginRight: 8,
    marginBottom: 8,
  },
  statusButtonActive: {
    backgroundColor: COLORS.green,
  },
  statusButtonDisabled: {
    opacity: 0.5,
  },
  statusButtonText: {
    color: COLORS.black,
    fontWeight: '600',
    fontSize: 14,
    textTransform: 'capitalize',
  },
  statusButtonTextActive: {
    color: COLORS.white,
  },
  currentStatusBadge: {
    padding: 14,
    borderRadius: 12,
  },
  currentStatusText: {
    fontSize: 15,
    color: COLORS.white,
    fontWeight: '600',
    textTransform: 'capitalize',
  },
});

export const consultantApplicationReviewScreenStyles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: COLORS.lightBackground,
  },
  scrollView: {
    flex: 1,
  },
  scrollContent: {
    padding: 16,
    paddingBottom: 24,
  },
  emptyContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
  },
  emptyText: {
    fontSize: 16,
    color: COLORS.gray,
  },
  matchBannerWrapper: {
    marginBottom: 20,
  },
  matchBanner: {
    backgroundColor: COLORS.white,
    borderRadius: 16,
    padding: 20,
    borderLeftWidth: 5,
    shadowColor: COLORS.black,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 8,
    elevation: 3,
  },
  matchBannerHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 16,
  },
  matchBadge: {
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 20,
    marginRight: 12,
  },
  matchBadgeText: {
    fontSize: 14,
    fontWeight: '700',
    color: COLORS.white,
    letterSpacing: 0.5,
  },
  matchBannerTitle: {
    fontSize: 20,
    fontWeight: '700',
    color: COLORS.black,
    letterSpacing: 0.5,
  },
  matchStatsRow: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingTop: 16,
    borderTopWidth: 1,
    borderTopColor: COLORS.lightBackground,
  },
  matchStat: {
    flex: 1,
    alignItems: 'center',
  },
  matchStatValue: {
    fontSize: 24,
    fontWeight: '700',
    color: COLORS.black,
    marginBottom: 4,
  },
  matchStatLabel: {
    fontSize: 12,
    color: COLORS.gray,
    fontWeight: '500',
  },
  matchStatDivider: {
    width: 1,
    height: 40,
    backgroundColor: COLORS.lightBackground,
    marginHorizontal: 16,
  },
  infoCard: {
    backgroundColor: COLORS.white,
    borderRadius: 16,
    padding: 20,
    marginBottom: 20,
    shadowColor: COLORS.black,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.08,
    shadowRadius: 8,
    elevation: 3,
  },
  cardTitle: {
    fontSize: 16,
    fontWeight: '600',
    color: COLORS.gray,
    marginBottom: 12,
  },
  applicantName: {
    fontSize: 22,
    fontWeight: '700',
    color: COLORS.black,
    marginBottom: 6,
  },
  applicantEmail: {
    fontSize: 15,
    color: COLORS.gray,
    fontWeight: '500',
  },
  section: {
    marginBottom: 24,
  },
  sectionTitle: {
    fontSize: 18,
    fontWeight: '700',
    color: COLORS.black,
    marginBottom: 16,
  },
  skillsGroup: {
    marginBottom: 20,
  },
  skillsGroupTitle: {
    fontSize: 15,
    fontWeight: '600',
    color: COLORS.green,
    marginBottom: 12,
  },
  skillsGroupTitleMissing: {
    fontSize: 15,
    fontWeight: '600',
    color: COLORS.red,
    marginBottom: 12,
  },
  skillsContainer: {
    flexDirection: 'row',
    flexWrap: 'wrap',
  },
  skillTag: {
    backgroundColor: COLORS.lightBackground,
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 16,
    marginRight: 8,
    marginBottom: 8,
    borderWidth: 1,
    borderColor: COLORS.lightGray,
  },
  skillText: {
    fontSize: 13,
    color: COLORS.gray,
    fontWeight: '500',
  },
  skillTagMatched: {
    backgroundColor: COLORS.green,
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 16,
    marginRight: 8,
    marginBottom: 8,
  },
  skillTextMatched: {
    fontSize: 13,
    color: COLORS.white,
    fontWeight: '600',
  },
  experienceCard: {
    backgroundColor: COLORS.white,
    borderRadius: 12,
    padding: 16,
    marginBottom: 12,
    borderWidth: 1,
    borderColor: COLORS.lightBackground,
  },
  experienceTitle: {
    fontSize: 17,
    fontWeight: '700',
    color: COLORS.black,
    marginBottom: 6,
  },
  experienceCompany: {
    fontSize: 15,
    color: COLORS.gray,
    marginBottom: 4,
    fontWeight: '500',
  },
  experienceDate: {
    fontSize: 13,
    color: COLORS.gray,
    marginBottom: 8,
  },
  experienceDescription: {
    fontSize: 14,
    color: COLORS.black,
    lineHeight: 20,
  },
  educationCard: {
    backgroundColor: COLORS.white,
    borderRadius: 12,
    padding: 16,
    marginBottom: 12,
    borderWidth: 1,
    borderColor: COLORS.lightBackground,
  },
  educationDegree: {
    fontSize: 17,
    fontWeight: '700',
    color: COLORS.black,
    marginBottom: 6,
  },
  educationInstitution: {
    fontSize: 15,
    color: COLORS.gray,
    marginBottom: 4,
    fontWeight: '500',
  },
  educationYear: {
    fontSize: 13,
    color: COLORS.gray,
  },
  backgroundText: {
    fontSize: 15,
    color: COLORS.black,
    lineHeight: 24,
    backgroundColor: COLORS.white,
    padding: 16,
    borderRadius: 12,
  },
  coverLetterText: {
    fontSize: 15,
    color: COLORS.black,
    lineHeight: 24,
    backgroundColor: COLORS.white,
    padding: 16,
    borderRadius: 12,
  },
  resumeButton: {
    backgroundColor: COLORS.green,
    padding: 16,
    borderRadius: 12,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 10,
  },
  resumeButtonText: {
    color: COLORS.white,
    fontSize: 16,
    fontWeight: '600',
  },
  statusButtonsContainer: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    marginBottom: 16,
  },
  statusButton: {
    backgroundColor: COLORS.lightBackground,
    paddingHorizontal: 20,
    paddingVertical: 14,
    borderRadius: 12,
    marginRight: 10,
    marginBottom: 10,
    minWidth: 100,
    alignItems: 'center',
  },
  statusButtonActive: {
    backgroundColor: COLORS.green,
  },
  statusButtonDisabled: {
    opacity: 0.5,
  },
  statusButtonText: {
    color: COLORS.black,
    fontWeight: '600',
    fontSize: 14,
    textTransform: 'capitalize',
  },
  statusButtonTextActive: {
    color: COLORS.white,
  },
});

