import { StyleSheet } from 'react-native';
import { COLORS } from '../core/colors';

export const authStyles = StyleSheet.create({
    container: {
        flex: 1,
        width: '100%',
        backgroundColor: COLORS.white,
        paddingHorizontal: 20,
    },
    loginContainer: {
        flex: 1,
        width: '100%',
    },
    authHeading: {
        fontSize: 30,
        fontWeight: '700',
        color: COLORS.black,
        marginBottom: 15,
    },
    formContainer: {
        width: '100%',
        flexGrow: 1,
        // paddingHorizontal: 20,
        paddingTop: 10,
        paddingBottom: 20,
    },
    screenFlex: {
        flex: 1,
    },
    scrollContainer: {
        flex: 1,
        width: '100%',
    },
    scrollContentContainer: {
        // paddingHorizontal: 20,
        paddingTop: 20,
        paddingBottom: 40,
        flexGrow: 1,
    },
    keyboardContent: {
        flexGrow: 1,
    },
    bottomContainer: {
        width: '100%',
        padding: 20,
        display: 'flex',
        alignItems: 'center',
        gap: 10,
        justifyContent: 'flex-end',
        backgroundColor: COLORS.white,
        marginTop: 'auto',
    },
    bottomSection: {
        width: '100%',
        paddingTop: 20,
        paddingBottom: 20,
        backgroundColor: COLORS.white,
    },
    label: {
        fontSize: 14,
        fontWeight: "400",
        lineHeight: 18,
        paddingVertical: 8,
    },
    inputWrapper: {
        flexDirection: "row",
        alignItems: "center",
        borderWidth: 1,
        borderColor: COLORS.lightGray,
        borderRadius: 8,
        paddingHorizontal: 12,
        marginBottom: 8,
    },
    input: {
        flex: 1,
        height: 56,
        color: COLORS.black,
        fontSize: 16,
    },
    forgotPassword: {
        alignSelf: 'flex-end',
        fontSize: 14,
        fontWeight: "400",
        color: COLORS.blackTransparent,
        marginBottom: 15,
        padding: 10,
    },
    signUpBtn: {
        backgroundColor: COLORS.yellow,
        paddingVertical: 14,
        borderRadius: 8,
        alignItems: "center",
        marginTop: 15,
        width: '100%',
        height: 56,
        justifyContent: 'center',
    },
    signUpText: {
        fontSize: 16,
        fontWeight: "bold",
        color: COLORS.black,
    },
    dividerWrapper: {
        flexDirection: "row",
        alignItems: "center",
        marginBottom: 10,
        width: '100%',
        height: 40,
        backgroundColor: COLORS.white,
        // paddingHorizontal: 20,
    },
    divider: {
        flex: 1,
        height: 1,
        backgroundColor: COLORS.blackTransparent,
    },
    dividerText: {
        marginHorizontal: 12,
        color: COLORS.blackTransparent,
        fontSize: 14,
    },
    socialRow: {
        flexDirection: "row",
        justifyContent: "center",
        marginBottom: 24,
        width: '100%',
        alignItems: 'center',
        gap: 12,
        flexWrap: 'wrap',
    },
    socialButton: {
        flex: 1,
        minWidth: 90,
        maxWidth: 120,
        height: 60,
        justifyContent: 'center',
        alignItems: 'stretch',
    },
    iconContainer: {
        width: '100%',
        height: 60,
        borderWidth: 1,
        borderColor: COLORS.lightGray,
        borderRadius: 12,
        backgroundColor: COLORS.white,
        justifyContent: 'center',
        alignItems: 'center',
        padding: 12,
    },
    icon: {
        width: 110,
        height: 60,
        // borderWidth: 1,
        // borderColor: COLORS.blackTransparent,
        borderStyle: 'solid',
        resizeMode: 'contain',
        borderRadius: 10,
        padding: 20,
    },
    socialIcon: {
        width: 36,
        height: 36,
    },
    back: {
        width: 14,
        height: 14,
        padding: 20,
        borderWidth: 1,
        borderColor: COLORS.blackTransparent,
        borderStyle: 'solid',
        borderRadius: 10,
    },
    footer: {
        textAlign: "center",
        color: COLORS.blackTransparent,
        width: '100%',
    },
    loginLink: {
        color: COLORS.black,
        fontWeight: "bold",
    },
    backButton: {
        padding: 18,
        backgroundColor: COLORS.white,
    },
    authPara: {
        fontSize: 16,
        lineHeight: 22,
        marginBottom: 20,
        fontWeight: "400",
        color: COLORS.blackTransparent,
    },
    box: {
        width: 77,
        height: 77,
        borderWidth: 1,
        borderColor: COLORS.blackTransparent,
        borderRadius: 16,
        textAlign: 'center',
        fontSize: 24,
        marginHorizontal: 4,
        backgroundColor: COLORS.white,
    },
    inputRow: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        marginBottom: 24
    },
    roleContainer: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        marginBottom: 20,
        gap: 10,
    },
    roleButton: {
        flex: 1,
        paddingVertical: 12,
        paddingHorizontal: 16,
        borderWidth: 1,
        borderColor: COLORS.lightGray,
        borderRadius: 8,
        alignItems: 'center',
        backgroundColor: COLORS.white,
    },
    roleButtonActive: {
        backgroundColor: COLORS.yellow,
        borderColor: COLORS.yellow,
    },
    roleButtonText: {
        fontSize: 14,
        fontWeight: '500',
        color: COLORS.blackTransparent,
    },
    roleButtonTextActive: {
        color: COLORS.black,
        fontWeight: '600',
    },
    loadingContainer: {
        alignItems: 'center',
        marginTop: 10,
    },
    passwordToggle: {
        padding: 8,
        justifyContent: 'center',
        alignItems: 'center',
    },
    errorMessage: {
        color: COLORS.red,
        fontSize: 14,
        fontWeight: '500',
        textAlign: 'center',
        marginTop: 10,
        paddingHorizontal: 16,
        backgroundColor: COLORS.red,
        paddingVertical: 8,
        borderRadius: 6,
        borderLeftWidth: 3,
        borderLeftColor: COLORS.red,
    },
    loader: {
        marginTop: 10,
    },
    profileImageContainer: {
        alignItems: 'center',
        marginVertical: 30,
    },
    profileImageWrapper: {
        position: 'relative',
    },
    cameraButton: {
        position: 'absolute',
        bottom: 0,
        right: 0,
        backgroundColor: COLORS.green,
        borderRadius: 20,
        padding: 8,
        borderWidth: 2,
        borderColor: COLORS.white,
    },
    cameraButtonSmall: {
        position: 'absolute',
        bottom: 0,
        right: 0,
        backgroundColor: COLORS.green,
        borderRadius: 15,
        padding: 6,
        borderWidth: 2,
        borderColor: COLORS.white,
    },
    removeImageButton: {
        marginTop: 15,
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: COLORS.red,
        paddingHorizontal: 20,
        paddingVertical: 10,
        borderRadius: 25,
    },
    removeImageText: {
        color: COLORS.white,
        marginLeft: 8,
        fontWeight: '500',
    },
    // Password validation styles
    passwordValidationContainer: {
        marginTop: 8,
        marginBottom: 8,
    },
    passwordStrengthBar: {
        height: 6,
        backgroundColor: COLORS.lightGray,
        borderRadius: 3,
        overflow: 'hidden',
        marginBottom: 8,
    },
    passwordStrengthFill: {
        height: '100%',
        borderRadius: 3,
    },
    passwordStrengthInfo: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        marginBottom: 8,
    },
    passwordStrengthText: {
        fontSize: 14,
        fontWeight: '600',
    },
    passwordFeedbackContainer: {
        backgroundColor: COLORS.white,
        padding: 12,
        borderRadius: 8,
        borderLeftWidth: 3,
        borderLeftColor: COLORS.blue,
        marginTop: 8,
    },
    passwordFeedbackTitle: {
        fontSize: 13,
        fontWeight: '600',
        color: COLORS.black,
        marginBottom: 6,
    },
    passwordFeedbackItem: {
        fontSize: 12,
        color: COLORS.gray,
        lineHeight: 18,
        marginBottom: 2,
    },
    passwordErrorContainer: {
        backgroundColor: COLORS.red,
        padding: 12,
        borderRadius: 8,
        borderLeftWidth: 3,
        borderLeftColor: COLORS.red,
        marginTop: 8,
    },
    passwordErrorTitle: {
        fontSize: 13,
        fontWeight: '600',
        color: COLORS.red,
        marginBottom: 6,
    },
    passwordErrorItem: {
        fontSize: 12,
        color: COLORS.red,
        lineHeight: 18,
        marginBottom: 2,
    },
    passwordSuccessContainer: {
        backgroundColor: COLORS.green,
        padding: 12,
        borderRadius: 8,
        borderLeftWidth: 3,
        borderLeftColor: COLORS.green,
        marginTop: 8,
    },
    passwordSuccessText: {
        fontSize: 13,
        fontWeight: '600',
        color: COLORS.green,
    },
});
