import { StyleSheet } from 'react-native';
import { COLORS } from '../core/colors';

export const callingStyles = StyleSheet.create({
  // Original calling screen styles
  container: {
    flex: 1,
    backgroundColor: COLORS.green,
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingTop: 20,
  },
  topBar: {
    width: '90%',
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: 20,
  },
  timeText: {
    color: COLORS.white,
    fontSize: 16,
    fontWeight: '600',
  },
  statusIcons: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  signalIcon: {
    width: 20,
    height: 12,
    backgroundColor: COLORS.white,
    borderRadius: 2,
  },
  wifiIcon: {
    width: 16,
    height: 12,
    backgroundColor: COLORS.white,
    borderRadius: 2,
  },
  batteryIcon: {
    width: 24,
    height: 12,
    backgroundColor: COLORS.white,
    borderRadius: 2,
  },
  profileContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    paddingHorizontal: 20,
    width: '100%',
  },
  profileImage: {
    width: 140,
    height: 140,
    borderRadius: 70,
    borderColor: COLORS.white,
    borderWidth: 4,
    shadowColor: COLORS.black,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 8,
    elevation: 8,
  },
  name: {
    color: COLORS.white,
    fontSize: 32,
    fontWeight: 'bold',
    marginTop: 24,
    textAlign: 'center',
    textShadowColor: 'rgba(0, 0, 0, 0.2)',
    textShadowOffset: { width: 0, height: 2 },
    textShadowRadius: 4,
  },
  status: {
    color: COLORS.white,
    fontSize: 18,
    marginTop: 12,
    opacity: 0.9,
    textAlign: 'center',
    fontWeight: '500',
  },
  buttonContainer: {
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    width: '100%',
    paddingHorizontal: 40,
    gap: 40,
  },
  iconButton: {
    width: 60,
    height: 60,
    borderRadius: 30,
    backgroundColor: COLORS.white,
    justifyContent: 'center',
    alignItems: 'center',
    shadowColor: COLORS.black,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.25,
    shadowRadius: 8,
    elevation: 8,
  },
  hangupButton: {
    backgroundColor: COLORS.red,
    transform: [{ rotate: '135deg' }],
  },
  acceptButton: {
    backgroundColor: COLORS.black,
    width: 70,
    height: 70,
    borderRadius: 35,
    shadowColor: COLORS.black,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 8,
    elevation: 8,
  },
  declineButton: {
    backgroundColor: COLORS.red,
    width: 70,
    height: 70,
    borderRadius: 35,
    shadowColor: COLORS.red,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 8,
    elevation: 8,
  },

  // Video calling screen styles
  videoCallContainer: {
    flex: 1,
    backgroundColor: COLORS.black,
  },
  mainVideoFeed: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    width: '100%',
    height: '100%',
  },
  topStatusBar: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: 20,
    paddingVertical: 10,
    zIndex: 10,
  },
  statusTime: {
    color: COLORS.white,
    fontSize: 16,
    fontWeight: '600',
  },
  videoStatusIcons: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  videoWifiIcon: {
    width: 16,
    height: 12,
    backgroundColor: COLORS.white,
    borderRadius: 2,
  },
  videoBatteryIcon: {
    width: 24,
    height: 12,
    backgroundColor: COLORS.white,
    borderRadius: 2,
  },
  bottomControls: {
    position: 'absolute',
    left: 0,
    right: 0,
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    gap: 40,
    zIndex: 10,
    paddingHorizontal: 40,
  },
  controlButton: {
    width: 60,
    height: 60,
    borderRadius: 30,
    backgroundColor: COLORS.white,
    justifyContent: 'center',
    alignItems: 'center',
    shadowColor: COLORS.black,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.25,
    shadowRadius: 8,
    elevation: 8,
  },
  videoHangupButton: {
    backgroundColor: COLORS.red,
    width: 60,
    height: 60,
    borderRadius: 30,
  },
  // Accept button for video calls (reuse acceptButton styles)
  videoAcceptButton: {
    backgroundColor: COLORS.green,
    width: 70,
    height: 70,
    borderRadius: 35,
    shadowColor: COLORS.green,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 8,
    elevation: 8,
  },
  // Decline button for video calls (reuse declineButton styles)
  videoDeclineButton: {
    backgroundColor: COLORS.red,
    width: 70,
    height: 70,
    borderRadius: 35,
    shadowColor: COLORS.red,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 8,
    elevation: 8,
  },
  insetVideoContainer: {
    position: 'absolute',
    right: 20,
    width: 120,
    height: 160,
    borderRadius: 12,
    overflow: 'hidden',
    zIndex: 10,
    borderWidth: 3,
    borderColor: COLORS.white,
    shadowColor: COLORS.black,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 8,
    elevation: 8,
  },
  insetVideo: {
    width: '100%',
    height: '100%',
  },
});
