import { StyleSheet } from 'react-native';
import { COLORS } from '../core/colors';

export const consultantApplicationsScreenStyles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: COLORS.white,
  },
  loadingContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: COLORS.white,
  },
  loadingText: {
    marginTop: 12,
    fontSize: 16,
    color: COLORS.gray,
  },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 20,
    paddingVertical: 16,
    paddingTop: 20,
    backgroundColor: COLORS.white,
    borderBottomWidth: 1,
    borderBottomColor: COLORS.lightGray,
  },
  headerButton: {
    width: 24,
    alignItems: 'center',
  },
  headerTitle: {
    fontSize: 18,
    fontWeight: '600',
    color: COLORS.black,
    flex: 1,
    textAlign: 'center',
  },
  statsContainer: {
    flexDirection: 'row',
    gap: 12,
    paddingHorizontal: 20,
    paddingVertical: 16,
    flexWrap: 'wrap',
    justifyContent: 'space-between',
  },
  statCard: {
    flex: 1,
    padding: 16,
    borderRadius: 12,
    alignItems: 'center',
  },
  statValue: {
    fontSize: 24,
    fontWeight: '700',
    marginBottom: 4,
  },
  statLabel: {
    fontSize: 12,
    fontWeight: '600',
  },
  statCardPending: {
    backgroundColor: COLORS.yellow,
  },
  statValuePending: {
    color: COLORS.orange,
  },
  statLabelPending: {
    color: COLORS.orange,
  },
  statCardApproved: {
    backgroundColor: COLORS.green,
  },
  statValueApproved: {
    color: COLORS.white,
  },
  statLabelApproved: {
    color: COLORS.white,
  },
  statCardRejected: {
    backgroundColor: COLORS.red,
  },
  statValueRejected: {
    color: COLORS.white,
  },
  statLabelRejected: {
    color: COLORS.white,
  },
  scrollView: {
    flex: 1,
  },
  emptyState: {
    alignItems: 'center',
    paddingVertical: 60,
    paddingHorizontal: 40,
  },
  emptyTitle: {
    fontSize: 18,
    fontWeight: '600',
    color: COLORS.black,
    marginTop: 16,
  },
  emptyText: {
    fontSize: 14,
    color: COLORS.gray,
    marginTop: 8,
  },
  emptyButton: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: COLORS.green,
    paddingHorizontal: 20,
    paddingVertical: 12,
    borderRadius: 8,
    marginTop: 20,
    gap: 8,
  },
  emptyButtonText: {
    color: COLORS.white,
    fontSize: 14,
    fontWeight: '600',
  },
  applicationsList: {
    paddingHorizontal: 20,
    gap: 12,
  },
  applicationCard: {
    backgroundColor: COLORS.white,
    padding: 16,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: COLORS.lightGray,
  },
  cardHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 12,
  },
  statusBadge: {
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderRadius: 12,
  },
  statusContent: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
  },
  statusText: {
    fontSize: 12,
    fontWeight: '600',
  },
  cardTitle: {
    fontSize: 16,
    fontWeight: '600',
    color: COLORS.black,
    marginBottom: 8,
  },
  videoPreviewContainer: {
    width: '100%',
    height: '100%',
    position: 'relative',
  },
  playButtonOverlay: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: 'rgba(0, 0, 0, 0.3)',
  },
  playButtonText: {
    color: COLORS.white,
    fontSize: 48,
    fontWeight: 'bold',
  },
  serviceImageContainer: {
    marginBottom: 12,
    borderRadius: 8,
    overflow: 'hidden',
  },
  serviceImage: {
    width: '100%',
    height: 120,
    borderRadius: 8,
  },
  cardDescription: {
    fontSize: 14,
    color: COLORS.gray,
    marginBottom: 8,
  },
  cardDetails: {
    flexDirection: 'row',
    gap: 8,
  },
  cardDetailText: {
    fontSize: 13,
    color: COLORS.lightGray,
  },
  reviewNotes: {
    marginTop: 12,
    padding: 12,
    backgroundColor: '#FEF2F2',
    borderRadius: 8,
    borderWidth: 1,
    borderColor: COLORS.red,
  },
  reviewNotesLabel: {
    fontSize: 12,
    fontWeight: '600',
    color: COLORS.red,
    marginBottom: 4,
  },
  reviewNotesText: {
    fontSize: 13,
    color: COLORS.black,
  },
  cardActions: {
    flexDirection: 'row',
    gap: 12,
    marginTop: 16,
  },
  editButton: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 10,
    borderRadius: 8,
    backgroundColor: '#E6F7EE',
    gap: 6,
  },
  editButtonText: {
    color: COLORS.green,
    fontSize: 14,
    fontWeight: '500',
  },
  deleteButton: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 10,
    borderRadius: 8,
    backgroundColor: '#FEE2E2',
    gap: 6,
    borderWidth: 1,
    borderColor: '#FECACA',
  },
  deleteButtonEmphasis: {
    backgroundColor: '#F87171',
    borderColor: '#F87171',
  },
  deleteButtonText: {
    color: COLORS.red,
    fontSize: 14,
    fontWeight: '500',
  },
  deleteButtonTextStrong: {
    color: COLORS.white,
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.5)',
    justifyContent: 'flex-end',
  },
  modalContent: {
    backgroundColor: COLORS.white,
    borderTopLeftRadius: 20,
    borderTopRightRadius: 20,
    paddingTop: 20,
    paddingBottom: 40,
    maxHeight: '90%',
  },
  modalHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 20,
    paddingBottom: 16,
    borderBottomWidth: 1,
    borderBottomColor: COLORS.lightGray,
  },
  modalTitle: {
    fontSize: 18,
    fontWeight: '600',
    color: COLORS.black,
  },
  modalForm: {
    paddingHorizontal: 20,
    paddingTop: 16,
  },
  inputContainer: {
    marginBottom: 16,
  },
  label: {
    fontSize: 14,
    fontWeight: '500',
    color: COLORS.black,
    marginBottom: 8,
  },
  input: {
    backgroundColor: COLORS.white,
    borderWidth: 1,
    borderColor: COLORS.lightGray,
    borderRadius: 8,
    paddingHorizontal: 12,
    paddingVertical: 10,
    fontSize: 14,
    color: COLORS.black,
  },
  imageUpload: {
    marginTop: 8,
  },
  textArea: {
    height: 100,
    textAlignVertical: 'top',
  },
  charCount: {
    fontSize: 12,
    color: COLORS.gray,
    marginTop: 4,
  },
  row: {
    flexDirection: 'row',
    gap: 12,
  },
  halfWidth: {
    width: '48%',
  },
  fullWidth: {
    width: '100%',
  },
  priceInput: {
    position: 'relative',
  },
  priceSymbol: {
    position: 'absolute',
    left: 12,
    top: 10,
    fontSize: 14,
    color: COLORS.gray,
    zIndex: 1,
  },
  priceInputField: {
    paddingLeft: 28,
  },
  modalActions: {
    flexDirection: 'row',
    gap: 12,
    paddingHorizontal: 20,
    paddingTop: 16,
  },
  cancelButton: {
    flex: 1,
    paddingVertical: 12,
    borderRadius: 8,
    backgroundColor: COLORS.lightGray,
    alignItems: 'center',
  },
  cancelButtonText: {
    color: COLORS.black,
    fontSize: 16,
    fontWeight: '600',
  },
  submitButton: {
    flex: 1,
    paddingVertical: 12,
    borderRadius: 8,
    backgroundColor: COLORS.green,
    alignItems: 'center',
  },
  submitButtonDisabled: {
    backgroundColor: COLORS.gray,
  },
  submitButtonText: {
    fontSize: 16,
    fontWeight: '600',
    // color: COLORS.white,
  },
  bottomSpacer: {
    height: 100,
  },
  // Access Type Styles
  accessTypeContainer: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
    marginBottom: 16,
  },
  accessTypeButton: {
    flex: 1,
    minWidth: 100,
    padding: 12,
    borderWidth: 1,
    borderColor: COLORS.lightGray,
    borderRadius: 8,
    backgroundColor: COLORS.white,
    alignItems: 'center',
    minHeight: 60,
  },
  accessTypeButtonActive: {
    borderColor: COLORS.green,
    backgroundColor: COLORS.green + '10',
  },
  accessTypeLabel: {
    fontSize: 14,
    fontWeight: '600',
    color: COLORS.black,
    marginBottom: 4,
  },
  accessTypeLabelActive: {
    color: COLORS.green,
  },
  accessTypeDescription: {
    fontSize: 11,
    color: COLORS.gray,
    textAlign: 'center',
  },
  pricingContainer: {
    marginBottom: 16,
  },
  // Category Styles
  categoryContainer: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
    marginBottom: 16,
  },
  categoryButton: {
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderWidth: 1,
    borderColor: COLORS.lightGray,
    borderRadius: 8,
    backgroundColor: COLORS.white,
    minWidth: 100,
    alignItems: 'center',
  },
  categoryButtonActive: {
    borderColor: COLORS.green,
    backgroundColor: COLORS.green + '10',
  },
  categoryButtonText: {
    fontSize: 12,
    fontWeight: '500',
    color: COLORS.black,
  },
  categoryButtonTextActive: {
    color: COLORS.green,
  },
  // Custom Category Input Styles
  addCategoryButton: {
    width: 40,
    height: 40,
    borderRadius: 8,
    backgroundColor: COLORS.green + '15',
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 1,
    borderColor: COLORS.green,
  },
  customCategoryInputContainer: {
    marginTop: 12,
    padding: 16,
    backgroundColor: COLORS.lightGray + '10',
    borderRadius: 8,
    borderLeftWidth: 3,
    borderLeftColor: COLORS.green,
  },
  customCategoryInput: {
    marginBottom: 12,
  },
  customCategoryButtons: {
    flexDirection: 'row',
    gap: 8,
  },
  customCategoryButton: {
    flex: 1,
    paddingVertical: 10,
    borderRadius: 6,
    alignItems: 'center',
  },
  customCategoryCancelButton: {
    backgroundColor: COLORS.lightGray,
  borderWidth: 1,
    borderColor: COLORS.gray,
  },
  customCategoryAddButton: {
    backgroundColor: COLORS.green,
  },
  customCategoryCancelText: {
    fontSize: 14,
    fontWeight: '500',
    color: COLORS.black,
  },
  customCategoryAddText: {
    fontSize: 14,
    fontWeight: '500',
    color: COLORS.white,
  },
  // Video Management Styles
  sectionHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 8,
  },
  addVideoButton: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderWidth: 1,
    borderColor: COLORS.green,
    borderRadius: 8,
    backgroundColor: COLORS.green + '10',
  },
  addVideoButtonText: {
    fontSize: 14,
    fontWeight: '500',
    color: COLORS.green,
  },
  videosList: {
    gap: 12,
  },
  videoItem: {
    flexDirection: 'row',
    gap: 12,
    padding: 12,
    borderWidth: 1,
    borderColor: COLORS.lightGray,
    borderRadius: 8,
    backgroundColor: COLORS.white,
  },
  videoThumbnail: {
    width: 80,
    height: 60,
    borderRadius: 6,
    overflow: 'hidden',
  },
  thumbnailImage: {
    width: '100%',
    height: '100%',
    borderRadius: 6,
  },
  placeholderThumbnail: {
    width: '100%',
    height: '100%',
    backgroundColor: COLORS.lightGray,
    justifyContent: 'center',
    alignItems: 'center',
    borderRadius: 6,
  },
  placeholderText: {
    fontSize: 20,
  },
  videoInfo: {
    flex: 1,
    justifyContent: 'center',
  },
  videoTitle: {
    fontSize: 14,
    fontWeight: '600',
    color: COLORS.black,
    marginBottom: 4,
  },
  videoDescription: {
    fontSize: 12,
    color: COLORS.gray,
    marginBottom: 4,
  },
  videoDuration: {
    fontSize: 11,
    color: COLORS.gray,
  },
  removeVideoButton: {
    padding: 4,
    borderRadius: 4,
    backgroundColor: COLORS.red + '10',
    height: 24,
    width: 24,
    justifyContent: 'center',
    alignItems: 'center',
  },
  // Curriculum Styles
  curriculumInput: {
    marginBottom: 8,
  },
  // Certificate Styles
  certificateOption: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    padding: 12,
    borderWidth: 1,
    borderColor: COLORS.lightGray,
    borderRadius: 8,
    backgroundColor: COLORS.white,
  },
  checkbox: {
    width: 20,
    height: 20,
    borderWidth: 2,
    borderColor: COLORS.lightGray,
    borderRadius: 4,
    justifyContent: 'center',
    alignItems: 'center',
  },
  checkboxChecked: {
    backgroundColor: COLORS.green,
    borderColor: COLORS.green,
  },
  checkmark: {
    color: COLORS.white,
    fontSize: 12,
    fontWeight: 'bold',
  },
  certificateText: {
    fontSize: 14,
    color: COLORS.black,
  },
  certificateTemplates: {
    marginTop: 16,
  },
  templateContainer: {
    flexDirection: 'row',
    gap: 8,
    marginTop: 8,
  },
  templateButton: {
    paddingHorizontal: 16,
    paddingVertical: 8,
    borderWidth: 1,
    borderColor: COLORS.lightGray,
    borderRadius: 8,
    backgroundColor: COLORS.white,
    minWidth: 80,
    alignItems: 'center',
  },
  templateButtonActive: {
    borderColor: COLORS.green,
    backgroundColor: COLORS.green + '10',
  },
  templateButtonText: {
    fontSize: 12,
    fontWeight: '500',
    color: COLORS.black,
  },
  templateButtonTextActive: {
    color: COLORS.green,
  },
  // Modal Styles
  modalOverlay: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: 'rgba(0, 0, 0, 0.5)',
    justifyContent: 'center',
    alignItems: 'center',
    zIndex: 2000,
  },
  addCategoryModalContent: {
    backgroundColor: COLORS.white,
    borderRadius: 20,
    padding: 28,
    margin: 20,
    width: '92%',
    maxWidth: 420,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.12,
    shadowRadius: 16,
    elevation: 12,
  },
  addCategoryModalHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 24,
  },
  addCategoryModalTitle: {
    fontSize: 22,
    fontWeight: '700',
    color: COLORS.black,
    flex: 1,
  },
  addCategoryCloseButton: {
    padding: 10,
    borderRadius: 24,
    backgroundColor: COLORS.lightGray + '20',
    // height: 44,
    width: 44,
    justifyContent: 'center',
    alignItems: 'center',
  },
  addCategoryInput: {
    marginBottom: 24,
  },
  addCategoryModalButtons: {
    flexDirection: 'row',
    gap: 16,
    marginTop: 12,
  },
  addCategoryModalButton: {
    flex: 1,
    paddingVertical: 16,
    borderRadius: 12,
    alignItems: 'center',
  },
  addCategoryCancelButton: {
    backgroundColor: COLORS.lightGray + '15',
    borderWidth: 1,
    borderColor: COLORS.lightGray + '30',
  },
  addCategoryAddButton: {
    backgroundColor: COLORS.green,
  },
  addCategoryCancelText: {
    fontSize: 16,
    fontWeight: '600',
    color: COLORS.black,
  },
  addCategoryAddText: {
    fontSize: 16,
    fontWeight: '600',
    color: COLORS.white,
  },
  // Full Screen Styles
  fullScreenOverlay: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: COLORS.lightBackground,
    zIndex: 1000,
  },
  fullScreenContainer: {
    flex: 1,
    backgroundColor: COLORS.lightBackground,
  },
  fullScreenHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 16,
    paddingVertical: 12,
    borderBottomWidth: 1,
    borderBottomColor: COLORS.lightGray,
    backgroundColor: COLORS.white,
  },
  backButton: {
    padding: 8,
    borderRadius: 20,
    backgroundColor: COLORS.lightGray + '20',
  },
  fullScreenTitle: {
    fontSize: 18,
    fontWeight: '600',
    color: COLORS.black,
    marginLeft: 16,
    flex: 1,
  },
  headerSpacer: {
    width: 40,
  },
  fullScreenContent: {
    flex: 1,
    paddingHorizontal: 16,
  },
  fullScreenSubmitContainer: {
    paddingHorizontal: 16,
    paddingVertical: 20,
    borderTopWidth: 1,
    borderTopColor: COLORS.lightGray,
    backgroundColor: COLORS.white,
  },
  fullScreenSubmitButton: {
    backgroundColor: COLORS.green,
    paddingVertical: 16,
    borderRadius: 12,
    alignItems: 'center',
  },
  fullScreenSubmitButtonDisabled: {
    backgroundColor: COLORS.gray,
  },
  fullScreenSubmitButtonText: {
    fontSize: 16,
    fontWeight: '600',
    color: COLORS.white,
  },
});
