import { StyleSheet } from 'react-native';
import { COLORS } from '../core/colors';

export const consultantServiceCardStyles = StyleSheet.create({
    card: {
        backgroundColor: COLORS.white,
        borderRadius: 16,
        shadowColor: '#000',
        shadowOpacity: 0.08,
        shadowOffset: { width: 0, height: 4 },
        shadowRadius: 12,
        elevation: 8,
        marginBottom: 16,
        width: '100%',
        minHeight: 320,
    },
    imageContainer: {
        width: '100%',
        height: 110,
        borderTopLeftRadius: 16,
        borderTopRightRadius: 16,
        overflow: 'hidden',
    },
    image: {
        width: '100%',
        height: '100%',
        resizeMode: 'cover',
    },
    placeholderImage: {
        width: '100%',
        height: '100%',
        backgroundColor: '#F8F9FA',
        justifyContent: 'center',
        alignItems: 'center',
    },
    placeholderIcon: {
        fontSize: 32,
        marginBottom: 8,
    },
    placeholderText: {
        fontSize: 14,
        color: '#6B7280',
        fontWeight: '500',
    },
    customImageBackground: {
        width: '100%',
        height: '100%',
        backgroundColor: '#059669',
        justifyContent: 'center',
        alignItems: 'center',
        paddingHorizontal: 16,
    },
    customImageText: {
        fontSize: 18,
        fontWeight: 'bold',
        color: 'white',
        textAlign: 'center',
        lineHeight: 22,
    },
    imageLoadingOverlay: {
        position: 'absolute',
        top: 0,
        left: 0,
        right: 0,
        bottom: 0,
        backgroundColor: 'rgba(0, 0, 0, 0.5)',
        justifyContent: 'center',
        alignItems: 'center',
    },
    imageLoadingText: {
        color: 'white',
        fontSize: 14,
        fontWeight: '500',
    },
    content: {
        padding: 12,
        flex: 1,
        justifyContent: 'flex-start',
    },
    contentTop: {
        flex: 0,
        flexGrow: 1,
    },
    title: {
        fontSize: 15,
        fontWeight: '700',
        color: COLORS.black,
        marginBottom: 6,
        lineHeight: 18,
        flex: 0,
    },
    durationBadge: {
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: '#E8F5E8',
        paddingHorizontal: 12,
        paddingVertical: 6,
        borderRadius: 20,
        alignSelf: 'flex-start',
        marginBottom: 10,
        shadowColor: '#000',
        shadowOpacity: 0.05,
        shadowOffset: { width: 0, height: 2 },
        shadowRadius: 4,
        elevation: 2,
    },
    durationText: {
        fontSize: 13,
        fontWeight: '600',
        color: COLORS.green,
        marginLeft: 4,
    },
    descriptionContainer: {
        marginBottom: 8,
    },
    description: {
        fontSize: 13,
        color: '#555',
        lineHeight: 20,
    },
    readMoreButton: {
        alignSelf: 'flex-start',
        paddingVertical: 4,
        paddingHorizontal: 0,
        marginTop: 4,
    },
    readMoreText: {
        fontSize: 13,
        fontWeight: '600',
        color: COLORS.green,
    },
    bookButton: {
        backgroundColor: COLORS.yellow,
        paddingVertical: 12,
        borderRadius: 12,
        alignItems: 'center',
        justifyContent: 'center',
        shadowColor: COLORS.black,
        shadowOpacity: 0.15,
        shadowOffset: { width: 0, height: 4 },
        shadowRadius: 8,
        elevation: 6,
        flex: 0,
    },
    bookButtonText: {
        fontSize: 15,
        fontWeight: '700',
        color: COLORS.black,
    },


    modalOverlay: {
        flex: 1,
        backgroundColor: 'rgba(0, 0, 0, 0.5)',
        justifyContent: 'flex-end',
    },
    modalContent: {
        backgroundColor: COLORS.white,
        borderTopLeftRadius: 20,
        borderTopRightRadius: 20,
        maxHeight: '85%',
        width: '100%',
    },
    modalHeader: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        paddingHorizontal: 20,
        paddingVertical: 16,
        borderBottomWidth: 1,
        borderBottomColor: '#E5E5E5',
    },
    modalTitle: {
        fontSize: 20,
        fontWeight: '700',
        color: COLORS.black,
        flex: 1,
        marginRight: 12,
    },
    closeButton: {
        padding: 4,
    },
    modalBody: {
        flex: 1,
        paddingHorizontal: 20,
        paddingTop: 20,
    },
    modalImage: {
        width: '100%',
        height: 200,
        borderRadius: 12,
        marginBottom: 16,
        resizeMode: 'cover',
    },
    modalPlaceholderImage: {
        width: '100%',
        height: 200,
        borderRadius: 12,
        backgroundColor: COLORS.gray,
        justifyContent: 'center',
        alignItems: 'center',
        marginBottom: 16,
    },
    modalDurationBadge: {
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: '#E8F5E8',
        paddingHorizontal: 12,
        paddingVertical: 6,
        borderRadius: 16,
        alignSelf: 'flex-start',
        marginBottom: 16,
    },
    modalDescription: {
        fontSize: 15,
        lineHeight: 24,
        color: COLORS.gray,
        marginBottom: 20,
    },
    modalFooter: {
        padding: 20,
        borderTopWidth: 1,
        borderTopColor: '#E5E5E5',
    },
    modalButton: {
        backgroundColor: COLORS.green,
        paddingVertical: 14,
        borderRadius: 8,
        alignItems: 'center',
        justifyContent: 'center',
    },
    modalButtonText: {
        fontSize: 16,
        fontWeight: '700',
        color: COLORS.white,
    },
});
