import { StyleSheet } from 'react-native';
import { COLORS } from '../core/colors';

export const helpStyles = StyleSheet.create({
  section: {
    marginTop: 24,
  },
  sectionTitle: {
    fontSize: 18,
    fontWeight: '600',
    color: COLORS.black,
    marginBottom: 16,
  },
  emailCard: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: COLORS.white,
    padding: 16,
    borderRadius: 12,
    marginBottom: 12,
    borderWidth: 1,
    borderColor: COLORS.lightGray,
    shadowColor: COLORS.black,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 3,
  },
  contactIcon: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: COLORS.chatInputBackground,
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 12,
  },
  contactContent: {
    flex: 1,
  },
  contactTitle: {
    fontSize: 16,
    fontWeight: '600',
    color: COLORS.black,
    marginBottom: 4,
  },
  emailAddress: {
    fontSize: 16,
    fontWeight: '600',
    color: COLORS.green,
    marginBottom: 4,
  },
  responseTime: {
    fontSize: 12,
    color: COLORS.gray,
    fontStyle: 'italic',
  },
  appInfo: {
    marginTop: 32,
    alignItems: 'center',
    paddingVertical: 20,
  },
  appInfoText: {
    fontSize: 12,
    color: COLORS.gray,
    marginBottom: 4,
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.4)',
    justifyContent: 'center',
    padding: 20,
  },
  modalContainer: {
    backgroundColor: COLORS.white,
    borderRadius: 16,
    maxHeight: '90%',
    overflow: 'hidden',
  },
  modalHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 20,
    paddingVertical: 16,
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: COLORS.lightGray,
  },
  modalTitle: {
    fontSize: 18,
    fontWeight: '600',
    color: COLORS.black,
  },
  modalCloseButton: {
    padding: 4,
  },
  modalCloseText: {
    fontSize: 20,
    color: COLORS.gray,
  },
  modalBody: {
    paddingHorizontal: 20,
  },
  modalBodyContent: {
    paddingBottom: 24,
  },
  modalDescription: {
    fontSize: 14,
    color: COLORS.gray,
    marginVertical: 16,
  },
  inputGroup: {
    marginBottom: 16,
  },
  inputLabel: {
    fontSize: 14,
    fontWeight: '600',
    color: COLORS.black,
    marginBottom: 6,
  },
  input: {
    borderWidth: 1,
    borderColor: COLORS.lightGray,
    borderRadius: 10,
    paddingVertical: 12,
    paddingHorizontal: 14,
    fontSize: 14,
    color: COLORS.black,
    backgroundColor: COLORS.white,
  },
  textArea: {
    minHeight: 120,
  },
  textAreaCompact: {
    minHeight: 90,
    textAlignVertical: 'top',
  },
  submitButton: {
    backgroundColor: COLORS.green,
    borderRadius: 10,
    paddingVertical: 14,
    alignItems: 'center',
    marginTop: 8,
  },
  submitButtonDisabled: {
    opacity: 0.6,
  },
  submitButtonText: {
    color: COLORS.white,
    fontSize: 16,
    fontWeight: '600',
  },
  providerRow: {
    flexDirection: 'row',
    marginBottom: 12,
    gap: 8,
  },
  providerChip: {
    borderWidth: 1,
    borderColor: COLORS.lightGray,
    borderRadius: 16,
    paddingHorizontal: 12,
    paddingVertical: 6,
    backgroundColor: COLORS.white,
    marginTop: 10,
  },
  providerChipActive: {
    backgroundColor: COLORS.green,
    borderColor: COLORS.green,
  },
  providerChipText: {
    fontSize: 13,
    color: COLORS.black,
    fontWeight: '600',
  },
  providerChipTextActive: {
    color: COLORS.white,
  },
  chatContainer: {
    maxHeight: 500,
    marginBottom: 12,
    padding: 10,
  },
  chatBubbleUser: {
    alignSelf: 'flex-end',
    backgroundColor: COLORS.blue,
    borderRadius: 12,
    padding: 10,
    marginBottom: 8,
    maxWidth: '90%',
  },
  chatBubbleAssistant: {
    alignSelf: 'flex-start',
    backgroundColor: '#F3F4F6',
    borderRadius: 12,
    padding: 10,
    marginBottom: 8,
    maxWidth: '90%',
  },
  chatBubbleText: {
    color: COLORS.black,
    fontSize: 14,
    lineHeight: 20,
  },
  chatBubbleTextUser: {
    color: COLORS.white,
  },
  chatInputRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  chatInput: {
    flex: 1,
    borderWidth: 1,
    borderColor: COLORS.lightGray,
    borderRadius: 10,
    paddingVertical: 10,
    paddingHorizontal: 12,
    color: COLORS.black,
    backgroundColor: COLORS.white,
    marginBottom: 10,
  },
  sendAiButton: {
    backgroundColor: COLORS.green,
    borderRadius: 10,
    paddingHorizontal: 14,
    paddingVertical: 11,
    marginBottom: 10,
  },
  sendAiButtonDisabled: {
    opacity: 0.7,
  },
  sendAiButtonText: {
    color: COLORS.white,
    fontWeight: '600',
    fontSize: 14,
  },
  debugOutputCard: {
    marginTop: 12,
    borderWidth: 1,
    borderColor: COLORS.lightGray,
    borderRadius: 10,
    padding: 12,
    backgroundColor: COLORS.white,
  },
  debugOutputText: {
    color: COLORS.black,
    fontSize: 14,
    lineHeight: 20,
  },
});
