import { StyleSheet } from 'react-native';
import { COLORS } from '../core/colors';

export const jobApplicationsScreenStyles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: COLORS.lightBackground,
  },
  scrollView: {
    flex: 1,
  },
  scrollContent: {
    padding: 16,
    paddingBottom: 24,
  },
  summaryCard: {
    backgroundColor: COLORS.white,
    borderRadius: 16,
    padding: 20,
    marginBottom: 20,
    shadowColor: COLORS.black,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.08,
    shadowRadius: 8,
    elevation: 3,
  },
  summaryTitle: {
    fontSize: 18,
    fontWeight: '700',
    color: COLORS.black,
    marginBottom: 16,
  },
  summaryStats: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 24,
  },
  summaryStat: {
    alignItems: 'center',
  },
  summaryLabel: {
    fontSize: 13,
    color: COLORS.gray,
    marginBottom: 6,
    fontWeight: '500',
  },
  summaryValue: {
    fontSize: 24,
    fontWeight: '700',
    color: COLORS.black,
  },
  emptyContainer: {
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 60,
    paddingHorizontal: 32,
  },
  emptyIcon: {
    fontSize: 64,
    marginBottom: 16,
  },
  emptyTitle: {
    fontSize: 20,
    fontWeight: '600',
    color: COLORS.black,
    marginBottom: 8,
    textAlign: 'center',
  },
  emptyText: {
    fontSize: 14,
    color: COLORS.gray,
    textAlign: 'center',
    lineHeight: 20,
  },
  applicationCard: {
    backgroundColor: COLORS.white,
    borderRadius: 16,
    padding: 16,
    marginBottom: 16,
    shadowColor: COLORS.black,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.08,
    shadowRadius: 8,
    elevation: 3,
    borderLeftWidth: 4,
  },
  cardHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
    marginBottom: 12,
  },
  titleContainer: {
    flex: 1,
    marginRight: 12,
  },
  applicantName: {
    fontSize: 18,
    fontWeight: '700',
    color: COLORS.black,
    marginBottom: 4,
  },
  applicantEmail: {
    fontSize: 14,
    color: COLORS.gray,
    fontWeight: '500',
  },
  ratingBadge: {
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: 12,
    minWidth: 70,
    alignItems: 'center',
  },
  ratingText: {
    fontSize: 11,
    fontWeight: '700',
    color: COLORS.white,
    letterSpacing: 0.5,
  },
  matchContainer: {
    marginBottom: 12,
    paddingBottom: 12,
    borderBottomWidth: 1,
    borderBottomColor: COLORS.lightBackground,
  },
  matchLabel: {
    fontSize: 12,
    color: COLORS.gray,
    marginBottom: 4,
    fontWeight: '500',
  },
  matchValue: {
    fontSize: 16,
    fontWeight: '600',
    color: COLORS.black,
  },
  skillsContainer: {
    marginBottom: 12,
  },
  skillsLabel: {
    fontSize: 12,
    color: COLORS.gray,
    marginBottom: 8,
    fontWeight: '600',
  },
  skillsList: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    alignItems: 'center',
  },
  skillTag: {
    backgroundColor: COLORS.green,
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 8,
    marginRight: 8,
    marginBottom: 8,
  },
  skillText: {
    fontSize: 12,
    color: COLORS.white,
    fontWeight: '600',
  },
  moreSkillsText: {
    fontSize: 12,
    color: COLORS.gray,
    fontStyle: 'italic',
  },
  footer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingTop: 12,
    borderTopWidth: 1,
    borderTopColor: COLORS.lightBackground,
  },
  statusBadge: {
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 8,
  },
  statusText: {
    fontSize: 12,
    fontWeight: '600',
    color: COLORS.white,
  },
  dateText: {
    fontSize: 12,
    color: COLORS.gray,
    fontWeight: '500',
  },
  summaryValueGold: {
    fontSize: 24,
    fontWeight: '700',
    color: '#FFD700',
  },
  summaryValueSilver: {
    fontSize: 24,
    fontWeight: '700',
    color: '#C0C0C0',
  },
  summaryValueBronze: {
    fontSize: 24,
    fontWeight: '700',
    color: '#CD7F32',
  },
  aiPanel: {
    backgroundColor: '#E8F4FF',
    borderWidth: 1,
    borderColor: '#B7DCFF',
    borderRadius: 12,
    padding: 12,
    marginBottom: 12,
  },
  aiPanelTitle: {
    fontSize: 15,
    fontWeight: '700',
    color: '#0B3A66',
    marginBottom: 6,
  },
  aiPanelText: {
    fontSize: 12,
    color: '#1F3B57',
    marginBottom: 4,
  },
  aiActionButton: {
    marginTop: 8,
    alignSelf: 'flex-start',
    backgroundColor: COLORS.green,
    borderRadius: 8,
    paddingVertical: 8,
    paddingHorizontal: 12,
  },
  aiActionButtonDisabled: {
    opacity: 0.7,
  },
  aiActionButtonText: {
    color: COLORS.white,
    fontSize: 12,
    fontWeight: '700',
  },
  shortagePanel: {
    backgroundColor: '#FFF4E8',
    borderWidth: 1,
    borderColor: '#FFD4A3',
    borderRadius: 12,
    padding: 12,
    marginBottom: 12,
  },
  shortageTitle: {
    fontSize: 15,
    fontWeight: '700',
    color: '#8A4A00',
    marginBottom: 6,
  },
  shortageText: {
    fontSize: 12,
    color: '#7A4F1D',
  },
  shortageAdviceBox: {
    marginTop: 10,
    backgroundColor: COLORS.white,
    borderRadius: 8,
    padding: 10,
  },
  shortageAdviceText: {
    fontSize: 12,
    color: COLORS.black,
    marginBottom: 4,
    lineHeight: 17,
  },
  readyNowBadge: {
    alignSelf: 'flex-start',
    backgroundColor: '#E8FFF2',
    borderColor: '#86D9AA',
    borderWidth: 1,
    borderRadius: 999,
    paddingHorizontal: 10,
    paddingVertical: 4,
    marginBottom: 8,
  },
  readyNowText: {
    color: '#106B3A',
    fontSize: 11,
    fontWeight: '700',
  },
  aiSubMetric: {
    marginTop: 6,
    fontSize: 12,
    color: COLORS.gray,
    lineHeight: 17,
  },
});
