import { StyleSheet } from "react-native";
import { COLORS } from "../core/colors";

export const message = StyleSheet.create({
    container: {
        width: '100%',
        height: '100%',
        backgroundColor: COLORS.white,
    },
    listContainer: {
        width: '100%',
        height: 102,
    },
    listHeader: {
        width: '100%',
        shadowColor: COLORS.black,
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        paddingVertical: 10,
    },
    heading : {
        fontSize: 18,
        fontWeight: 'bold',
        color: COLORS.black,
        paddingVertical: 5,
    },
    avatar: {
        width: 55,
        height: 55,
        borderRadius: 27.5, // Half of width/height for perfect circle
    },
    avatarContainer: {
        position: 'relative',
    },
    onlineIndicator: {
        position: 'absolute',
        top: 2,
        right: 2,
        width: 14,
        height: 14,
        borderRadius: 7,
        backgroundColor: COLORS.green,
        borderWidth: 2,
        borderColor: COLORS.white,
    },
    horizontalScrollContent: {
        paddingHorizontal: 20,
        alignItems: 'flex-start',
    },
    userItem: {
        marginRight: 15,
        alignItems: 'center',
    },
    messageContainer: {
        width: '100%',
        height: 80,
        borderRadius: 10,
        padding: 5,
        backgroundColor: '#C8EBCB47',
        overflow: 'visible' as const,
    },
    messageHeader: {
        width: '100%',
        height: 70,
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        overflow: 'visible' as const,
    },
    messageAvatar: {
        width: 55,
        height: 55,
        borderRadius: 27.5, 
    },
    messageNameContainer: {
        flex: 1,
        height: '100%',
        marginLeft: 10,
        flexDirection: 'column',
        alignItems: 'flex-start',
        justifyContent: 'center',
        gap: 5,
    },
    messageName: {
        fontSize: 16,
        fontWeight: 'bold',
        color: COLORS.black,
    },
    messageTimeContainer: {
        flex: 0,
        flexShrink: 0,
        flexDirection: 'column' as const,
        alignItems: 'center' as const,
        justifyContent: 'center' as const,
        marginLeft: 10,
        gap: 4,
        minWidth: 70,
        overflow: 'visible' as const,
    },
    messageTime: {
        fontSize: 12,
        color: COLORS.blackTransparent,
        fontWeight: 'bold',
        textAlign: 'center' as const,
    },
    badgeContainer: {
        minWidth: 24,
        height: 24,
        borderRadius: 12,
        backgroundColor: COLORS.green,
        justifyContent: 'center' as const,
        alignItems: 'center' as const,
        paddingHorizontal: 8,
        paddingVertical: 2,
        marginTop: 0,
        borderWidth: 2,
        borderColor: COLORS.white,
        alignSelf: 'center' as const,
    },
    badgeText: {
        color: COLORS.white,
        fontWeight: '700' as const,
        fontSize: 12,
        textAlign: 'center' as const,
        includeFontPadding: false,
        lineHeight: 14,
    },
        messageContent: {
        fontSize: 12,
        color: COLORS.blackTransparent,
    },
    messagesListContainer: {
        width: '100%',
        gap: 10,
    },
})  