import { StyleSheet } from 'react-native';
import { COLORS } from '../core/colors';

export const postJobScreenStyles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: COLORS.lightBackground,
  },
  scrollView: {
    flex: 1,
  },
  scrollContent: {
    padding: 16,
    paddingBottom: 24,
  },
  label: {
    fontSize: 14,
    fontWeight: '600',
    color: COLORS.black,
    marginBottom: 8,
    marginTop: 4,
  },
  input: {
    borderWidth: 1,
    borderColor: COLORS.lightGray,
    borderRadius: 12,
    padding: 14,
    marginBottom: 16,
    fontSize: 15,
    backgroundColor: COLORS.white,
    color: COLORS.black,
  },
  textArea: {
    minHeight: 120,
    textAlignVertical: 'top',
    paddingTop: 14,
  },
  jobTypeContainer: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    marginBottom: 16,
    gap: 10,
  },
  jobTypeButton: {
    backgroundColor: COLORS.lightBackground,
    paddingHorizontal: 18,
    paddingVertical: 10,
    borderRadius: 10,
    marginRight: 8,
    marginBottom: 8,
  },
  jobTypeButtonActive: {
    backgroundColor: COLORS.green,
  },
  jobTypeText: {
    color: COLORS.black,
    fontWeight: '500',
    fontSize: 14,
    textTransform: 'capitalize',
  },
  jobTypeTextActive: {
    color: COLORS.white,
    fontWeight: '600',
  },
  addSkillContainer: {
    flexDirection: 'row',
    marginBottom: 12,
  },
  addSkillInput: {
    flex: 1,
    borderWidth: 1,
    borderColor: COLORS.lightGray,
    borderRadius: 12,
    padding: 14,
    marginRight: 8,
    fontSize: 15,
    backgroundColor: COLORS.white,
    color: COLORS.black,
  },
  addButton: {
    backgroundColor: COLORS.green,
    width: 48,
    height: 48,
    borderRadius: 12,
    justifyContent: 'center',
    alignItems: 'center',
  },
  skillsContainer: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    marginBottom: 16,
  },
  skillTag: {
    backgroundColor: COLORS.green,
    paddingHorizontal: 14,
    paddingVertical: 8,
    borderRadius: 20,
    marginRight: 10,
    marginBottom: 10,
    flexDirection: 'row',
    alignItems: 'center',
  },
  skillText: {
    color: COLORS.white,
    fontSize: 13,
    fontWeight: '600',
    marginRight: 8,
  },
  removeSkillButton: {
    padding: 2,
  },
  rowContainer: {
    flexDirection: 'row',
    gap: 12,
    marginBottom: 16,
  },
  halfWidth: {
    flex: 1,
  },
  submitButton: {
    marginTop: 8,
  },
  salaryRowContainer: {
    flexDirection: 'row',
    gap: 8,
    marginBottom: 16,
    alignItems: 'flex-start',
  },
  currencySelectorButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    borderWidth: 1,
    borderColor: COLORS.lightGray,
    borderRadius: 12,
    paddingHorizontal: 12,
    paddingVertical: 14,
    backgroundColor: COLORS.white,
    minWidth: 80,
    maxWidth: 100,
  },
  currencySelectorText: {
    fontSize: 15,
    fontWeight: '600',
    color: COLORS.black,
    marginRight: 4,
  },
  salaryInputWrapper: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    borderWidth: 1,
    borderColor: COLORS.lightGray,
    borderRadius: 12,
    backgroundColor: COLORS.white,
  },
  currencyPrefix: {
    fontSize: 14,
    fontWeight: '600',
    color: COLORS.gray,
    paddingLeft: 12,
    paddingRight: 6,
  },
  salaryInput: {
    flex: 1,
    marginBottom: 0,
    borderWidth: 0,
    paddingLeft: 0,
    paddingVertical: 14,
    fontSize: 15,
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0, 0, 0, 0.5)',
    justifyContent: 'flex-end',
  },
  modalContent: {
    backgroundColor: COLORS.white,
    borderTopLeftRadius: 20,
    borderTopRightRadius: 20,
    paddingBottom: 20,
    maxHeight: '70%',
  },
  modalHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    padding: 20,
    borderBottomWidth: 1,
    borderBottomColor: '#F0F0F0',
  },
  modalTitle: {
    fontSize: 18,
    fontWeight: '600',
    color: COLORS.black,
  },
  currencyList: {
    maxHeight: 400,
  },
  currencyOption: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    padding: 16,
    borderBottomWidth: 1,
    borderBottomColor: '#F0F0F0',
  },
  currencyOptionActive: {
    backgroundColor: '#F0F8F0',
  },
  currencyOptionLeft: {
    flexDirection: 'row',
    alignItems: 'center',
    flex: 1,
  },
  currencyOptionCode: {
    fontSize: 16,
    fontWeight: '600',
    color: COLORS.black,
    width: 60,
  },
  currencyOptionSymbol: {
    fontSize: 16,
    fontWeight: '500',
    color: COLORS.gray,
    width: 50,
  },
  currencyOptionName: {
    fontSize: 15,
    color: COLORS.black,
    flex: 1,
  },
  currencyCheckmark: {
    fontSize: 18,
    color: COLORS.green,
    fontWeight: 'bold',
  },
});

