import { StyleSheet } from 'react-native';
import { COLORS } from '../core/colors';

export const serviceCardStyles = StyleSheet.create({
  card: {
    backgroundColor: COLORS.white,
    borderRadius: 16,
    shadowColor: COLORS.black,
    shadowOpacity: 0.25,
    shadowOffset: { width: 0, height: 8 },
    shadowRadius: 20,
    elevation: 12,
    marginBottom: 16,
    width: '48%',
    flexDirection: 'column',
  },
  imageContainer: {
    position: 'relative',
    width: '100%',
    height: 140,
  },
  image: {
    width: '100%',
    height: '100%',
    resizeMode: 'cover',
    borderTopRightRadius: 16,
    borderTopLeftRadius: 16,
  },
  videoContainer: {
    width: '100%',
    height: '100%',
    position: 'relative',
    borderTopRightRadius: 16,
    borderTopLeftRadius: 16,
    overflow: 'hidden',
  },
  playButton: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: 'rgba(0, 0, 0, 0.3)',
  },
  playButtonInner: {
    width: 60,
    height: 60,
    borderRadius: 30,
    backgroundColor: 'rgba(255, 255, 255, 0.9)',
    justifyContent: 'center',
    alignItems: 'center',
    shadowColor: COLORS.black,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.3,
    shadowRadius: 4,
    elevation: 5,
  },
  playIcon: {
    fontSize: 24,
    color: COLORS.green,
    marginLeft: 4,
  },
  placeholderContainer: {
    width: '100%',
    height: '100%',
    backgroundColor: COLORS.gray,
    justifyContent: 'center',
    alignItems: 'center',
    borderTopRightRadius: 16,
    borderTopLeftRadius: 16,
  },
  placeholderText: {
    color: COLORS.white,
    fontSize: 14,
    fontWeight: '600',
    textAlign: 'center',
    paddingHorizontal: 12,
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0, 0, 0, 0.9)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  modalContent: {
    width: '90%',
    maxWidth: 500,
    backgroundColor: COLORS.white,
    borderRadius: 16,
    padding: 20,
    alignItems: 'center',
  },
  closeButton: {
    position: 'absolute',
    top: 10,
    right: 10,
    width: 30,
    height: 30,
    borderRadius: 15,
    backgroundColor: COLORS.gray,
    justifyContent: 'center',
    alignItems: 'center',
  },
  closeButtonText: {
    fontSize: 18,
    color: COLORS.white,
    fontWeight: 'bold',
  },
  videoLinkButton: {
    backgroundColor: COLORS.green,
    paddingVertical: 12,
    paddingHorizontal: 24,
    borderRadius: 8,
    marginTop: 20,
  },
  videoLinkText: {
    color: COLORS.white,
    fontSize: 16,
    fontWeight: '600',
  },
  durationBadge: {
    position: 'absolute',
    top: 12,
    right: 12,
    backgroundColor: COLORS.green,
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: 20,
    shadowColor: COLORS.black,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.2,
    shadowRadius: 6,
    elevation: 5,
  },
  durationIcon: {
    fontSize: 12,
    color: COLORS.white,
    marginRight: 4,
  },
  durationText: {
    fontSize: 12,
    color: COLORS.white,
    fontWeight: '600',
  },
  contentContainer: {
    padding: 12,
    flex: 1,
    justifyContent: 'space-between',
    flexDirection: 'column',
  },
  textContent: {
    flex: 1,
    justifyContent: 'flex-start',
  },
  title: {
    fontSize: 16,
    fontWeight: '700',
    color: COLORS.black,
    marginBottom: 6,
    lineHeight: 20,
  },
  consultantInfo: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 8,
    width: '100%',
  },
  priceRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 8,
  },
  priceLabel: {
    fontSize: 12,
    color: COLORS.gray,
    fontWeight: '500',
  },
  priceValue: {
    fontSize: 16,
    color: COLORS.green,
    fontWeight: '700',
  },
  consultantInfoExpanded: {
    flexDirection: 'column',
    alignItems: 'flex-start',
    width: '100%',
  },
  consultantText: {
    fontSize: 14,
    color: COLORS.gray,
    fontWeight: '500',
    flex: 1,
  },
  consultantCategoryText: {
    fontSize: 14,
    color: COLORS.gray,
    fontWeight: '500',
    marginTop: 4,
  },
  description: {
    fontSize: 13,
    lineHeight: 18,
    color: '#666666',
    marginBottom: 6,
  },
  readMoreButton: {
    alignSelf: 'flex-start',
    paddingVertical: 2,
    marginBottom: 12,
  },
  readMoreText: {
    fontSize: 13,
    color: COLORS.green,
    fontWeight: '600',
  },
  button: {
    backgroundColor: COLORS.green,
    paddingVertical: 12,
    paddingHorizontal: 16,
    borderRadius: 10,
    minHeight: 44,
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: COLORS.green,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.4,
    shadowRadius: 8,
    elevation: 6,
    marginTop: 'auto',
  },
  buttonText: {
    fontSize: 14,
    fontWeight: '700',
    color: COLORS.white,
    textAlign: 'center',
  },
});

